### PR TITLE
`line` output format. Closes #114

### LINKED ISSUE #114: Add an output format of "line" (similar to \gx in postgres)
Here is an example from osquery:
```
osquery> .mode line
osquery> SELECT pid, name, path FROM processes LIMIT 1;
  pid = 1
 name = launchd
 path = /sbin/launchd
osquery> .mode pretty
```

### PR DESCRIPTION
**Pull request by binaek89**
*In interactive mode*

Screenshot 2021-02-02 at 4 09 12 PM

*in batch mode* 

Screenshot 2021-02-02 at 4 10 23 PM

### CODE REVIEW

**Comment by binaek89** [comment]
@e-gineer @johnsmyth can you take a look at the outputs and give feedback?

**Comment by kaidaguerre** [comment]
@e-gineer format is the same as osquery. Nulls are displayed the same an empty item after the equals sign, as per the screenshot

image

steampipe multiline:
image

**Comment by dboeke** [comment]
There should be a line separator.  In PostgeSQL the individual records look like:

```
-[ RECORD 1 ]---------------
id     | 1
uniq   | 1
val    | 3
val_ts | 2007-07-03 00:00:00
-[ RECORD 2 ]---------------
id     | 2
uniq   | 2
val    | 4
val_ts | 2007-07-03 00:00:00
```

and in my SQL they look like:

```
*************************** 1. row ***************************
help_keyword_id: 0
           name: JOIN
*************************** 2. row ***************************
help_keyword_id: 1
           name: REPEAT
*************************** 3. row ***************************
help_keyword_id: 2
```

I prefer the PostgreSQL approach.

**Comment by kaidaguerre** [comment]
so @dboeke so our current format copies the osquery centre justified approach. 

adding the postgresql header to the existing formatitng looks a bit weird
```
-[ RECORD 1 ]==================================================================================================================================================================================
                  name = turbot_1_admin
              group_id = AGPAQGDRKHTKPO2RUGYQC
                  path = /turbot/
                   arn = arn:aws:iam::013122550996:group/turbot/turbot_1_admin
           create_date = 2019-12-16 06:25:49
       inline_policies = 
  attached_policy_arns = ["arn:aws:iam::013122550996:policy/turbot/turbot_1_admin"]
                 users = 
                 title = turbot_1_admin
                  akas = ["arn:aws:iam::013122550996:group/turbot/turbot_1_admin"]
             partition = aws
                region = global
            account_id = 013122550996
-[ RECORD 2 ]==================================================================================================================================================================================
                  name = iam_metadata
              group_id = AGPAQGDRKHTKK32J26RXM
                  path = /turbot/
                   arn = arn:aws:iam::013122550996:group/turbot/iam_metadata
           create_date = 2019-11-28 08:21:26
       inline_policies = 
  attached_policy_arns = ["arn:aws:iam::013122550996:policy/turbot/turbot_iam_metadata"]
                 users = 
                 title = iam_metadata
                  akas = ["arn:aws:iam::013122550996:group/turbot/iam_metadata"]
             partition = aws
                region = global
            account_id = 013122550996
```

**Comment by dboeke** [comment]
Yes, I think we should hold and get the format right.

**Comment by dboeke** [comment]
if we did the postgres approach it would look like:
```
-[ RECORD 1 ]-------------------------------------------------------------------------
name                 | turbot_1_admin
group_id             | AGPAQGDRKHTKPO2RUGYQC
path                 | /turbot/
arn                  | arn:aws:iam::013122550996:group/turbot/turbot_1_admin
create_date          | 2019-12-16 06:25:49
inline_policies      | 
attached_policy_arns | ["arn:aws:iam::013122550996:policy/turbot/turbot_1_admin"]
users                | 
title                | turbot_1_admin
akas                 | ["arn:aws:iam::013122550996:group/turbot/turbot_1_admin"]
partition            | aws
region               | global
account_id           | 013122550996
-[ RECORD 2 ]-------------------------------------------------------------------------
name                 | iam_metadata
group_id             | AGPAQGDRKHTKK32J26RXM
path                 | /turbot/
arn                  | arn:aws:iam::013122550996:group/turbot/iam_metadata
create_date          | 2019-11-28 08:21:26
inline_policies      | 
attached_policy_arns | ["arn:aws:iam::013122550996:policy/turbot/turbot_iam_metadata"]
users                | 
title                | iam_metadata
akas                 | ["arn:aws:iam::013122550996:group/turbot/iam_metadata"]
partition            | aws
region               | global
account_id           | 013122550996
```

**Comment by binaek89** [comment]
Aligned output with @dboeke's example from `psql`

```
steampipe query "select * from whois_domain where domain in ('steampipe.io','turbot.com')" --output line

-[ RECORD 1  ]---------------------------------------------------------------------------
domain                     | steampipe.io
domain_id                  | D503300001187474055-LRMS
domain_punycode            | steampipe.io
domain_extension           | io
whois_server               | whois.gandi.net
status                     | ["clienttransferprohibited","servertransferprohibited"]
name_servers               | ["ns-128.awsdns-16.com","ns-600.awsdns-11.net","ns-1628.awsdns-11.co.uk","ns-1455.awsdns-53.org"]
dns_sec                    | false
created_date               | 2020-10-13 19:28:29
updated_date               | 2020-12-12 20:32:56
expiration_date            | 2021-10-13 19:28:29
client_delete_prohibited   | false
client_transfer_prohibited | true
client_update_prohibited   | false
server_delete_prohibited   | false
server_transfer_prohibited | true
server_update_prohibited   | false
registrar                  | {"email":"abuse@support.gandi.net","id":"81","name":"GANDI SAS","phone":"+33.170377661","referral_url":"http://www.gandi.net"}
registrant                 | {"city":"New York","country":"US","email":"domains@turbot.com","id":"DA57879-GANDI","name":"Domain Administrator","organization":"Turbot HQ, Inc","phone":"+1.8882887268","postal_code":"10128","province":"New York","street":"1732 1st Ave #20232"}
admin                      | {"city":"New York","country":"US","email":"domains@turbot.com","id":"DA57879-GANDI","name":"Domain Administrator","organization":"Turbot HQ, Inc","phone":"+1.8882887268","postal_code":"10128","province":"New York","street":"1732 1st Ave #20232"}
technical                  | {"city":"New York","country":"US","email":"domains@turbot.com","id":"DA57879-GANDI","name":"Domain Administrator","organization":"Turbot HQ, Inc","phone":"+1.8882887268","postal_code":"10128","province":"New York","street":"1732 1st Ave #20232"}
billing                    | 

-[ RECORD 2  ]---------------------------------------------------------------------------
domain                     | turbot.com
domain_id                  | 168144065_DOMAIN_COM-VRSN
domain_punycode            | turbot.com
domain_extension           | com
whois_server               | whois.registrar.amazon.com
status                     | ["clienttransferprohibited"]
name_servers               | ["ns-1312.awsdns-36.org","ns-2039.awsdns-62.co.uk","ns-287.awsdns-35.com","ns-517.awsdns-00.net"]
dns_sec                    | false
created_date               | 2005-06-10 18:05:01
updated_date               | 2017-03-20 13:26:21
expiration_date            | 2022-06-10 18:05:01
client_delete_prohibited   | false
client_transfer_prohibited | true
client_update_prohibited   | false
server_delete_prohibited   | false
server_transfer_prohibited | false
server_update_prohibited   | false
registrar                  | {"email":"abuse@amazonaws.com","id":"468","name":"Amazon Registrar, Inc.","phone":"+1.2067406200","referral_url":"https://registrar.amazon.com"}
registrant                 | {"city":"Seattle","country":"US","email":"owner-6615959@turbot.com.whoisprivacyservice.org","name":"On behalf of turbot.com owner","organization":"Whois Privacy Service","phone":"+1.2065771368","postal_code":"98108-1226","province":"WA","street":"P.O. Box 81226"}
admin                      | {"city":"Seattle","country":"US","email":"admin-6615959@turbot.com.whoisprivacyservice.org","name":"On behalf of turbot.com administrative contact","organization":"Whois Privacy Service","phone":"+1.2065771368","postal_code":"98108-1226","province":"WA","street":"P.O. Box 81226"}
technical                  | {"city":"Seattle","country":"US","email":"tech-6615959@turbot.com.whoisprivacyservice.org","name":"On behalf of turbot.com technical contact","organization":"Whois Privacy Service","phone":"+1.2065771368","postal_code":"98108-1226","province":"WA","street":"P.O. Box 81226"}
billing                    | 
binaeksarkar@Binaeks-MacBook-Pro ~ % 
```

**Comment by binaek89** [comment]
`multiline` value in output:
```
steampipe query "select domain, domain_id, domain_extension, whois_server,jsonb_pretty(registrar) from whois_domain where domain in ('steampipe.io','turbot.com')" --output line
-[ RECORD 1  ]---------------------------------------------------
domain           | turbot.com                                        
domain_id        | 168144065_DOMAIN_COM-VRSN                         
domain_extension | com                                               
whois_server     | whois.registrar.amazon.com                        
jsonb_pretty     | {                                                  +
                 |     "id": "468",                                   +
                 |     "name": "Amazon Registrar, Inc.",              +
                 |     "email": "abuse@amazonaws.com",                +
                 |     "phone": "+1.2067406200",                      +
                 |     "referral_url": "https://registrar.amazon.com" +
                 | }                                                 
-[ RECORD 2  ]-------------------------------------------
domain           | steampipe.io                              
domain_id        | D503300001187474055-LRMS                  
domain_extension | io                                        
whois_server     | whois.gandi.net                           
jsonb_pretty     | {                                          +
                 |     "id": "81",                            +
                 |     "name": "GANDI SAS",                   +
                 |     "email": "abuse@support.gandi.net",    +
                 |     "phone": "+33.170377661",              +
                 |     "referral_url": "http://www.gandi.net" +
                 | }                                         
                                   
```

**Comment by dboeke** [comment]
Love it, looks great!

**Pull request merged**
