### PR TITLE
Improve plugin uninstall output when connections remain. Closes #1158

### LINKED ISSUE #1158: Improve plugin uninstall output when connections remain
the current output is a bit messy and confusing. Also the pluralising is wrong: 
```
$ sp plugin uninstall hackernews

The following file has steampipe connections using the 'hackernews' plugin:

        * 'hackernews' in /Users/kai/.steampipe/config/hackernews.spc, line 1

Please remove them to continue using steampipe

Uninstalled plugin hackernews
```

Maybe should be more like: 
```
$ sp plugin uninstall hackernews

Uninstalled plugin hackernews

Note: the following file has a steampipe connectionsusing the 'hackernews' plugin:
        *  file: /Users/kai/.steampipe/config/hackernews.spc 
           connection: 'hackernews' (line 1)

Please remove it to continue using steampipe
```

```
$ sp plugin uninstall hackernews

Uninstalled plugin hackernews

Note: the following file has steampipe connections using the 'hackernews' plugin:
        *  file: /Users/kai/.steampipe/config/hackernews.spc 
           connection: 'hackernews' (line 1)
           connection: 'hackernews2' (line 8)


Please remove it to continue using steampipe
```

```
$ sp plugin uninstall hackernews

Uninstalled plugin hackernews

Note: the following files have steampipe connections using the 'hackernews' plugin:
        *  file: /Users/kai/.steampipe/config/hackernews.spc 
           connection: 'hackernews' (line 1)
        *  file: /Users/kai/.steampipe/config/hackernews2.spc 
           connection: 'hackernews2' (line 1)
           connection: 'hackernews3' (line 8)

Please remove them to continue using steampipe
```

### PR DESCRIPTION
**Pull request by pskrbasu**
Screenshot 2021-12-09 at 11 34 11 AM

Screenshot 2021-12-09 at 11 52 10 AM

### CODE REVIEW

**Comment by kaidaguerre** [comment]
@pskrbasu can you give screenshots for each of the scenarios in the issue https://github.com/turbot/steampipe/issues/1158

note the pluralisation

**Comment by kaidaguerre** [comment]
@pskrbasu  one further request - please can you put `uninstalled plugi xxxx` first before the warning

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
@pskrbasu  one further request - please can you put `uninstalled plugin xxxx` first before the warning

**Comment by pskrbasu** [comment]
> @pskrbasu one further request - please can you put `uninstalled plugin xxxx` first before the warning

Changes made in 4072099bb4658a7ca136a146f671e61312edcf5c

**Pull request merged**
