### PR TITLE
add output flag to plugin list cmd

### LINKED ISSUE #3368: json output for plugin list command
It would be nice to have a `--output json` flag with the plugin list output, just like the other list commands.

### PR DESCRIPTION
**Pull request by Mr-Destructive**
Fix #3368 

Have added the `--output` flag as a string flag for the plugin list command. Do I create a separate method for it or is it fine?

Let me know of any further changes.
Thank you.

### CODE REVIEW

**Comment by pskrbasu** [comment]
@Mr-Destructive Thank you for the PR. I'll look into it and let you know if any changes are required at all.
Before that, can you please attach a screenshot of the resulting JSON output in this PR, for better visibility?

Thanks!

**Comment by Mr-Destructive** [comment]
Sure, here is the screenshot for the output flag with json

steampipe plugin list --output json Result


Would you like the flag to suppress the table output?

**Comment by binaek** [comment]
@Mr-Destructive thank you for the PR. The `--output` flag should behave similar to how `--output` behaves for `steampipe query` - with the only difference being that the possible values for `--output` in `plugin list` are `table` and `json`

**Review by binaek — CHANGES_REQUESTED** [review]
Hi @Mr-Destructive , thank you for the updates.

I feel that the approach needs a bit more clarity.

Take a look at [ShowOutput](https://github.com/turbot/steampipe/blob/60c9cfb7cca2322dbbe8c295b2d7c4b237eb2818/pkg/display/display.go#L30) in the [display](https://github.com/turbot/steampipe/blob/60c9cfb7cca2322dbbe8c295b2d7c4b237eb2818/pkg/display) package.

We should have a function `showPluginListOutput(pluginList, failedPluginMap, missingPluginMap...)`

`showPluginListOutput` should be similar to [ShowOutput](https://github.com/turbot/steampipe/blob/60c9cfb7cca2322dbbe8c295b2d7c4b237eb2818/pkg/display/display.go#L30) and branch out to `displayAsTable` and `displayAsJson` depending on the value of `viper.GetString(constants.ArgOutput)`

Thanks

**Comment by pskrbasu** [comment]
Hey @Mr-Destructive, sorry for the late response. We are still reviewing internally how the JSON structure should look, and we will come back to you soon.

Thanks

**Comment by Mr-Destructive** [comment]
Cool, No issues :+1:

**Comment by binaek** [comment]
@Mr-Destructive while we zero down on the `json` output structure, can you add a couple of tests to verify the `table` and `json` outputs?

Please use the tests for `query` as a reference.

[chaos_and_query.bats](https://github.com/turbot/steampipe/blob/033ad9f33e296e2064eb8373493c060fdd0cc3a6/tests/acceptance/test_files/chaos_and_query.bats)

**Comment by pskrbasu** [comment]
@Mr-Destructive We have finalised a structure for our plugin list JSON output.

Here's an example output of `steampipe plugin list --output json` we want
```
{
  "installed": [
    {
      "name": "hub.steampipe.io/plugins/turbot/algolia@latest",
      "version": "0.3.0",
      "connections": [
        "algolia"
      ]
    },
    {
      "name": "hub.steampipe.io/plugins/turbot/aws@latest",
      "version": "0.103.0",
      "connections": [
        "aws"
      ]
    }
  ],
  "failed": [
    {
      "name": "hub.steampipe.io/plugins/turbot/twitter@latest",
      "reason": "Not installed",
      "connections": [
        "twitter"
      ]
    }
  ]
}
```
NOTE: We group the failed+missing plugins in one table here in [plugin.go#L596](https://github.com/turbot/steampipe/blob/main/cmd/plugin.go#L596)


The table output currently looks like this:
```
+------------------------------------------------+---------+-------------+
| Installed Plugin                               | Version | Connections |
+------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/algolia@latest | 0.3.0   | algolia     |
| hub.steampipe.io/plugins/turbot/aws@latest     | 0.103.0 | aws         |
+------------------------------------------------+---------+-------------+

+------------------------------------------------+-------------+---------------+
| Failed Plugin                                  | Connections | Reason        |
+------------------------------------------------+-------------+---------------+
| hub.steampipe.io/plugins/turbot/twitter@latest | twitter     | Not installed |
+------------------------------------------------+-------------+---------------+
```

We also want to change the headers of the tables: 
```
Installed Plugin --> Installed
Failed Plugin --> Failed
```
Could you please update the header names in [plugin.go#L587](https://github.com/turbot/steampipe/blob/main/cmd/plugin.go#L587) and [plugin.go#L599](https://github.com/turbot/steampipe/blob/main/cmd/plugin.go#L599) too while you're working in this area?

Hope the above JSON structure is understandable. In case of any questions/blockers/help required please feel free to ask me or @binaek. We are always ready to help you out.

Thanks!

**Comment by Mr-Destructive** [comment]
Yes, I will look into it and try to do it soon, maybe over the weekend.

**Comment by Mr-Destructive** [comment]
So, the warnings and missing plugins should be removeed right? The missing plugins should be added to the failed plugin list or ignore them?

**Comment by pskrbasu** [comment]
> 

Yes @Mr-Destructive the warnings and missing plugins should be removed, and we add the missing plugins to the Failed table. See https://github.com/turbot/steampipe/blob/main/cmd/plugin.go#L596.

**Comment by Mr-Destructive** [comment]
I have updated the format for the list command. Please review and suggest further changes. 

Meanwhile, I am writing the tests for them.

**Comment by pskrbasu** [comment]
@Mr-Destructive I have added some comments.

The `Failed` table and `failed` struct should contain both the failedPluginMap and missingPluginMap from the `getPluginList()` function.

Here's a way to test this:
- install a plugin(eg. hackernews)
- uninstall the plugin
- do not remove the config file($INSTALL_DIR/config/hackernews.spc)
- running `steampipe plugin list` would give you the `Failed` table with hackernews listed.

We need to replicate the same for the JSON output.

Please take a look and let us know if you still have any doubts, we can help you out.

Thanks

**Review by pskrbasu — COMMENTED** [review]
@Mr-Destructive I have added some comments.

The `Failed` table and `failed` struct should contain both the failedPluginMap and missingPluginMap from the `getPluginList()` function.

Here's a way to test this:
- install a plugin(eg. hackernews)
- uninstall the plugin
- do not remove the config file($INSTALL_DIR/config/hackernews.spc)
- running `steampipe plugin list` would give you the `Failed` table with hackernews listed.

We need to replicate the same for the JSON output.

Please take a look and let us know if you still have any doubts, we can help you out.

Thanks

**Comment by pskrbasu** [comment]
@Mr-Destructive I have added some comments.

The `Failed` table and `failed` struct should contain both the failedPluginMap and missingPluginMap from the `getPluginList()` function.

Here's a way to test this:
- install a plugin(eg. hackernews)
- uninstall the plugin
- do not remove the config file($INSTALL_DIR/config/hackernews.spc)
- running `steampipe plugin list` would give you the `Failed` table with hackernews listed.

We need to replicate the same for the JSON output.

Please take a look and let us know if you still have any doubts, we can help you out.

Thanks

**Comment by Mr-Destructive** [comment]
I am trying to test the code changes but it doesn't add it to the failed plugins list. There are some print statements in the screenshots, just for debugging the failed and missing plugin map which is also empty.

image
image
image

I'm sorry it's taking so long, but I haven't been able to test for failed plugins.

**Review by pskrbasu — COMMENTED** [review]
@Mr-Destructive Your branch seems to be quite behind our latest main. We have made a lot of changes(fixes) around connection states recently, which I guess might be affecting the plugin list behaviour in your outdated branch.

Please rebase your branch with our latest main and try re-running. Hopefully, that will solve your issue.
Also, we have added a couple of plugin list tests in [service_and_plugin.bats](https://github.com/turbot/steampipe/blob/main/tests/acceptance/test_files/service_and_plugin.bats). Those tests will be available once you rebase your branch. You can add your JSON output test there.

Let us know if your changes work as expected after rebasing, and then we can review the code.

Thanks

**Comment by Mr-Destructive** [comment]
I think I have messed up this PR, I will create a new branch and raise a new PR.

**Pull request closed without merging**
