### PR TITLE
Cloud and workspace flags should not be Global Flags as they are not used for all commands. Closes #3542

### LINKED ISSUE #3542: Service(server level) commands should not accept client connection arguments
There are 2 types of steampipe commands, server and client:
- Server commands are only for running locally(eg: service, plugin), you cannot connect to a remote database using these commands.
- Client commands can be run by connecting them to a remote database(eg: query, dashboard etc.).

`steampipe service` is a server-level command that can only be used locally, and `steampipe service start` can only start a local server. So steampipe service should not have client args like `--workspace-database`. Neither should it honour the client env vars like `STEAMPIPE_WORKSPACE_DATABASE`. 

TODO: 
- Identify and rectify these situations wherever necessary.
- Update https://steampipe.io/docs/reference/env-vars/steampipe_workspace_database

### PR DESCRIPTION
**Pull request by pskrbasu**
### service

existing:
Screenshot 2023-08-18 at 4 42 07 PM
new:
Screenshot 2023-09-12 at 4 06 43 PM

### query

existing:
Screenshot 2023-08-18 at 4 43 24 PM
new:
Screenshot 2023-09-12 at 4 07 08 PM

### check

existing:
Screenshot 2023-08-18 at 4 44 01 PM
new:
Screenshot 2023-09-12 at 4 07 39 PM

### dashboard

existing:
Screenshot 2023-08-18 at 4 44 42 PM
new:
Screenshot 2023-09-12 at 4 08 14 PM

### plugin

existing:
Screenshot 2023-08-18 at 4 45 27 PM
new:
Screenshot 2023-09-12 at 4 09 00 PM

### mod

existing:
Screenshot 2023-08-18 at 4 45 58 PM
new:
Screenshot 2023-09-12 at 4 09 27 PM

### variable

existing:
Screenshot 2023-08-18 at 4 46 46 PM
new:
Screenshot 2023-09-12 at 4 09 56 PM

### login

existing:
Screenshot 2023-08-18 at 4 59 45 PM

new:
Screenshot 2023-09-12 at 4 10 18 PM

### completion

existing:
Screenshot 2023-08-18 at 4 59 23 PM

new:
Screenshot 2023-09-12 at 4 10 38 PM

### CODE REVIEW

**Review by binaek — CHANGES_REQUESTED** [review]

**Comment by pskrbasu** [comment]
Docs updated https://github.com/turbot/steampipe-docs/pull/156

**Review by johnsmyth — APPROVED** [review]

**Review by johnsmyth — COMMENTED** [review]
@pskrbasu: 
- What do `--workspace` and `--workspace-database` do when passed to `steampipe login`?
- does / should `--mod-location` apply so the `steampipe mod` commands

**Review by johnsmyth — COMMENTED** [review]
@pskrbasu: 
- What do `--workspace` and `--workspace-database` do when passed to `steampipe login`?
- does / should `--mod-location` apply so the `steampipe mod` commands

**Comment by pskrbasu** [comment]
@johnsmyth 

> What do `--workspace` and `--workspace-database` do when passed to `steampipe login`?

- `--workspace` makes sense for `steampipe login` since it can contain the `cloud-host` and `cloud-token` properties.
- `--workspace-database` does not make sense for `steampipe login` since we login as a user and cannot login to any particular pipes workspace. (I will remove the --workspace-database flag for login)

> does / should `--mod-location` apply so the `steampipe mod` commands

- `--mod-location` **does and should apply** to `steampipe mod` commands. It was a mistake to omit them. I will add those flags back to mod commands.

**Pull request merged**
