### PR TITLE
Add errcheck(1)

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by e-gineer** [comment]
Just a quick note to say thanks @gliptak ... really appreciate all the work you've been doing to review and tidy up the code.

Particularly love error handling improvements! Great contributions 🚀

**Comment by gliptak** [comment]
@e-gineer you are welcome

This PR fails acceptance tests (triggering a latent bug?). Any pointers on what additional changes required to correct?

**Comment by kaidaguerre** [comment]
I'll take a look and see what the issue is

**Comment by gliptak** [comment]
build is green

**Comment by kaidaguerre** [comment]
thanks @gliptak!

**Pull request merged**
