### PR TITLE
Update deprecated set-output and use GITHUB_OUTPUT environment files in our workflows. Closes #2572

### LINKED ISSUE #2572: Update deprecated `set-output` and use `GITHUB_OUTPUT` environment files in our workflows
GitHub actions is deprecating `save-state` and `set-output` commands. We use the `set-output` command in our acceptance tests and other workflows. Time to update.
Screenshot 2022-10-21 at 5 26 15 PM

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
… in the workflows

### CODE REVIEW

**Comment by SaumyaBhushan** [comment]
https://github.com/turbot/steampipe/issues/2572

**Comment by pskrbasu** [comment]
@SaumyaBhushan we have another instance of `set-output` used in https://github.com/turbot/steampipe/blob/main/tests/acceptance/run.sh#L68 ( where we set the exit_code from our tests, to use in the GitHub workflow). Can you take a look and update that so it doesn't break our test suite when deprecated?

**Comment by SaumyaBhushan** [comment]
Hi @pskrbasu Please review.

**Comment by SaumyaBhushan** [comment]
Hi, @pskrbasu Do these changes look good to you?

**Comment by pskrbasu** [comment]
Thank you @SaumyaBhushan, the changes look great and again thanks for the contribution.

**Pull request merged**
