### PR TITLE
Add a helpful error message when snapshot sharing fails because of a corrupted/invalid token. Closes #2944

### LINKED ISSUE #2944: Running `steampipe ... --share` with an invalid/corrupted token gives an unhelpful error message
```
steampipe ✗ steampipe query "select 1 as val, 2 as col" --share
Error: 400 Bad Request
```

### PR DESCRIPTION
**Pull request by pskrbasu**
Screenshot 2023-01-25 at 6 14 24 PM

### CODE REVIEW

**Review by kaidaguerre — COMMENTED** [review]
How does this compare to the display of `MissingCloudTokenError`:
```
 MissingCloudTokenError = errors.New("Not authenticated for Steampipe Cloud.\nPlease run 'steampipe login' or setup a token.")
```

**Comment by pskrbasu** [comment]
> How does this compare to the display of `MissingCloudTokenError`:
> 
> ```
>  MissingCloudTokenError = errors.New("Not authenticated for Steampipe Cloud.\nPlease run 'steampipe login' or setup a token.")
> ```

We get the `MissingCloudTokenError` when the user is not logged in. This PR handles the error when the cloud token stored in cloud.steampipe.io.sptt file gets corrupted somehow and we receive an unhelpful `400 Bad Request` error .

**Comment by kaidaguerre** [comment]
> > How does this compare to the display of `MissingCloudTokenError`:
> > ```
> >  MissingCloudTokenError = errors.New("Not authenticated for Steampipe Cloud.\nPlease run 'steampipe login' or setup a token.")
> > ```
> 
> We get the `MissingCloudTokenError` when the user is not logged in. This PR handles the error when the cloud token stored in cloud.steampipe.io.sptt file gets corrupted somehow and we receive an unhelpful `400 Bad Request` error .

right but my point is the output should be consistent, i.e. if the command is bolded in one, it should be in both

**Comment by pskrbasu** [comment]
https://github.com/turbot/steampipe/pull/3069

**Pull request closed without merging**
