### PR TITLE
Set dashboard timeout with env

### PR DESCRIPTION
**Pull request by taliesins**
When you have a lot of dashboards it may take more then 30 seconds to start up especially in a resource contained environment i.e. running it in a container in Kubernetes

### CODE REVIEW

**Comment by taliesins** [comment]
This is #3373 rebased with latest master

**Comment by taliesins** [comment]
@binaek can you approve the workflow

**Comment by binaek** [comment]
Approved the workflow

I will have a look at the code changes as soon as I clear off a couple of things from my plate.

**Comment by binaek** [comment]
Can you add a few tests for the feature?

**Comment by binaek** [comment]
@taliesins it looks like some of the unit tests are failing. Can you take a look? I think we should also add a few acceptance tests for the feature that you are adding.

**Comment by binaek** [comment]
Hi @taliesins . We have opened up a new [issue](https://github.com/turbot/steampipe/issues/3657) so that we can look at the acceptance tests for this feature separately.

You can take a look at it separately if you get the chance - we can takeover the acceptance tests if you are otherwise occupied.

**Comment by pskrbasu** [comment]
Hey, @taliesins I took the liberty of fixing the unit tests for you. I have raised a PR https://github.com/taliesins/steampipe/pull/3 (directed to this branch) which would fix the tests.

We are very keen to get this feature released with our v0.21.0 release since it also fixes a long-existing bug as well. So if you could merge my PR and rebase your branch with our latest main, it would be great.

Please let us know if you have any questions. Thanks for the hard work!

**Comment by binaek** [comment]
Closed by #3721

**Pull request closed without merging**
