### PR TITLE
fix: sorted plugins

### LINKED ISSUE #2501: Plugins in steampipe plugin update --all should be sorted alphabetically
Current output is not sorted and would be much easier to read if it was:
```
~/src $ steampipe plugin update --all

turbot/algolia       [====================================================================] Latest already installed      
turbot/twitter       [====================================================================] Latest already installed      
turbot/whois         [====================================================================] Latest already installed      
turbot/csv           [====================================================================] Done                
turbot/reddit        [====================================================================] Latest already installed      
turbot/slack         [====================================================================] Latest already installed      
turbot/aws           [====================================================================] Latest already installed      
turbot/virustotal    [====================================================================] Latest already installed      
turbot/ipstack       [====================================================================] Latest already installed      
turbot/terraform     [====================================================================] Latest already installed      
turbot/hackernews    [====================================================================] Latest already installed      
turbot/rss           [====================================================================] Latest already installed      
turbot/github        [====================================================================] Done                
turbot/net           [====================================================================] Latest already installed      
turbot/steampipeclo… [====================================================================] Latest already installed      
turbot/trivy         [====================================================================] Latest already installed      
turbot/config        [====================================================================] Latest already installed      


Updated plugin: csv@latest v0.4.0
Documentation:  https://hub.steampipe.io/plugins/turbot/csv

Updated plugin: github@latest v0.21.0
Documentation:  https://hub.steampipe.io/plugins/turbot/github

~/src $ 
```

### PR DESCRIPTION
**Pull request by himanshu007-creator**
resolves  #2501

### CODE REVIEW

**Comment by kaidaguerre** [comment]
Thanks @himanshu007-creator,  turned out to be a nice easy fix.

Please could you upload a screenshot to make it easy to verify this has done the trick?

**Comment by himanshu007-creator** [comment]
Hey! @kaidaguerre , 
i just read the code, and found out that list of plugins to update is generated here
https://github.com/himanshu007-creator/steampipe/blob/himanshu-sorted-plugins/cmd/plugin.go#L509-L525

So i tested my sorting logic in Go playground, and implemented it. If you can share instructions to test it locally that would be really helpful.

**Comment by kaidaguerre** [comment]
Hi @himanshu007-creator 

If you run install a number of plugins, by running, for example, 
```
steampipe plugin install aws gcp azure github
```

**Comment by himanshu007-creator** [comment]
Hi @kaidaguerre , i followed the above steps, but the result was not alphabetically sorted. I am confused on the part that how can i make sure i am using **My version of Steampipe**, the one i made changes in. Is there any way i can particularly test that only?

i installed steampipe using the <code>install.sh</code> but think it merely installs it from remote, not from the source i made changes in.

**Comment by binaek** [comment]
@himanshu007-creator Thank you for your efforts. 

You need to install `go` to be able to build `steampipe`. You can find documentation on how to install `go` in https://go.dev/doc/install

 `steampipe` comes with a `Makefile` which builds from your source and replaces the binary which is installed by `install.sh` when you run `make` in the `steampipe` source code root.

Alternatively, if you don't have `make`, then I suggest that you run `go build -o /usr/local/bin/steampipe` in your source code root.

The best way to make sure that you are running the version built from source is to tweak the `prerelease` variable in `pkg/version/version.go` and then running `steampipe --version`.

Hope this helps! Please get back if you need any further help.

**Comment by binaek** [comment]
@himanshu007-creator are you still looking at this? I can take it up if you have other things on your plate.

If you are still working on this, I found a bug which may be causing this issue.

The following change should work for you:
* update `line#31` in `pkg/utils/map.go` to `sort.Strings(keys)` instead of `sort.Strings(maps.Keys(m))`.

The issue occurs because there's a bug there which is not actually sorting the `keys` variable.

There may be other changes that you need to do - this is just a one that I could spot.

**Comment by himanshu007-creator** [comment]
Hey @binaek , feel free to take this issue, its festival season so couldn;t work on it

**Comment by kaidaguerre** [comment]
Ok closing this now, thanks for the time spent @himanshu007-creator

**Pull request closed without merging**
